name: Build and deploy to Render

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  workflow-a:
   name: Java CI with Maven
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Verify Target Directory
      run: ls -la target

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: akotorrii/my-private-repo
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  workflow-b:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: workflow-a
    if: github.event_name == 'push' && needs.workflow-a.result == 'success'
    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST -d '{}' \
        -H "Accept: application/json" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        https://api.render.com/v1/services/srv-crbht3a3esus73923rh0/deploys
