name: Deploy to Render

on:
  push:
    branches: [ "master" ]
  workflow_run:
    workflows: ["Java CI with Maven"]  
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST -d '{}' \
        -H "Accept: application/json" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        https://api.render.com/v1/services/srv-crbht3a3esus73923rh0/deploys
