name: Deploy to Render

on: 
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download marker file
      uses: actions/download-artifact@v2
      with:
        name: marker-file
        path: ./

    - name: Check for marker file
      id: marker-check
      run: |
        if [ ! -f .workflow-a-success ]; then
          echo "Marker file not found. Exiting."
          exit 1
        fi

    - name: Trigger Render Deploy
      run: |
        curl -X POST -d '{}' \
        -H "Accept: application/json" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        https://api.render.com/v1/services/srv-crbht3a3esus73923rh0/deploys
